In [60]:
import pandas as pd
import datetime
import matplotlib.pyplot as plt
%matplotlib inline
#textblob to apply sentiment analysis 
from textblob import TextBlob
import random

In [61]:
#read the csv file containing musks tweets
tweets = pd.read_csv('../using_twint/musks_tweets.csv')
tweets.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,retweets_count,likes_count,location,hashtags,cashtags,link,retweet,quote_url,video,profile_image_url
0,945814723521417217,945712432416137217,1514334777000,2017-12-26,19:32:57,EDT,44196397,elonmusk,Elon Musk,NaN,...,70,2497,NaN,[],[],https://twitter.com/elonmusk/status/9458147235...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
1,945749747129659392,945712432416137217,1514319285000,2017-12-26,15:14:45,EDT,44196397,elonmusk,Elon Musk,NaN,...,88,3123,NaN,[],[],https://twitter.com/elonmusk/status/9457497471...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
2,945748731197980672,945712432416137217,1514319043000,2017-12-26,15:10:43,EDT,44196397,elonmusk,Elon Musk,NaN,...,103,2946,NaN,[],[],https://twitter.com/elonmusk/status/9457487311...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
3,945730195113365504,945727773493968896,1514314623000,2017-12-26,13:57:03,EDT,44196397,elonmusk,Elon Musk,NaN,...,127,5076,NaN,[],[],https://twitter.com/elonmusk/status/9457301951...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
4,945729852874694656,945712432416137217,1514314542000,2017-12-26,13:55:42,EDT,44196397,elonmusk,Elon Musk,NaN,...,104,3374,NaN,[],[],https://twitter.com/elonmusk/status/9457298528...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...

In [62]:
#get a particular tweet text
some_tweet = tweets.iloc[random.randint(1, 100)]['tweet']
print(some_tweet)
#get the 'sentiment' of a particular tweet 
analysis = TextBlob(some_tweet)
print(analysis.sentiment)

Sorry
Sentiment(polarity=-0.5, subjectivity=1.0)

In [63]:
#store sentiments into dataframe
#I DONT KNOW HOW TO GET THIS TO WORK?? 
for index, row in tweets.iterrows():
    text = tweets.iloc[index]['tweet']
    analysis = TextBlob(text)
    row['Polarity'] = analysis.sentiment[0]
    row['Subjectivity'] = analysis.sentiment[1]

In [64]:
tweets.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,retweets_count,likes_count,location,hashtags,cashtags,link,retweet,quote_url,video,profile_image_url
0,945814723521417217,945712432416137217,1514334777000,2017-12-26,19:32:57,EDT,44196397,elonmusk,Elon Musk,NaN,...,70,2497,NaN,[],[],https://twitter.com/elonmusk/status/9458147235...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
1,945749747129659392,945712432416137217,1514319285000,2017-12-26,15:14:45,EDT,44196397,elonmusk,Elon Musk,NaN,...,88,3123,NaN,[],[],https://twitter.com/elonmusk/status/9457497471...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
2,945748731197980672,945712432416137217,1514319043000,2017-12-26,15:10:43,EDT,44196397,elonmusk,Elon Musk,NaN,...,103,2946,NaN,[],[],https://twitter.com/elonmusk/status/9457487311...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
3,945730195113365504,945727773493968896,1514314623000,2017-12-26,13:57:03,EDT,44196397,elonmusk,Elon Musk,NaN,...,127,5076,NaN,[],[],https://twitter.com/elonmusk/status/9457301951...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...
4,945729852874694656,945712432416137217,1514314542000,2017-12-26,13:55:42,EDT,44196397,elonmusk,Elon Musk,NaN,...,104,3374,NaN,[],[],https://twitter.com/elonmusk/status/9457298528...,NaN,NaN,0,https://pbs.twimg.com/profile_images/113234336...